/* assets_data.h - baked-in image textures for the WASM renderer.
 * Generated by bake_assets.py. Do not edit manually. */
#ifndef ASSETS_DATA_H
#define ASSETS_DATA_H

#include <stdint.h>

/* Texture lookup table */
typedef struct { const uint32_t *pixels; int w, h; } baked_tex_t;
#define BAKED_TEX_COUNT 12
static const baked_tex_t BAKED_TEX[] = {
  { tex_char_runner_pixels, tex_char_runner_W, tex_char_runner_H },
  { tex_char_skater_pixels, tex_char_skater_W, tex_char_skater_H },
  { tex_char_child_pixels, tex_char_child_W, tex_char_child_H },
  { tex_crumbling_pixels, tex_crumbling_W, tex_crumbling_H },
  { tex_warnstripes_pixels, tex_warnstripes_W, tex_warnstripes_H },
  { tex_icetile_pixels, tex_icetile_W, tex_icetile_H },
  { tex_ruinedtile_pixels, tex_ruinedtile_W, tex_ruinedtile_H },
  { tex_balloon_pixels, tex_balloon_W, tex_balloon_H },
  { tex_plus_pixels, tex_plus_W, tex_plus_H },
  { tex_arrow_pixels, tex_arrow_W, tex_arrow_H },
  { tex_battery_pixels, tex_battery_W, tex_battery_H },
  { tex_accel_pixels, tex_accel_W, tex_accel_H },
};

#endif /* ASSETS_DATA_H */
