/* custom_cutscenes.js - original dialogue for the custom extended tunnels,
 * plus curated per-cutscene CAST tables (custom + original).
 * Companion to cutscenes.js (which is generated by bake_cutscenes.py from
 * the decompiled SWF — do not put custom content there or the next rebake
 * wipes it). Loaded after cutscenes.js, before app.js. Merges into
 * window.STORY_CUT, extends window.STORY_PATH_CUT to ids 30-35, and adds
 * window.STORY_END_CHAIN (tunnel id -> sequel cutscene played once after
 * the tunnel's regular end cutscene) and window.STORY_CAST
 * (cutscene name -> [leftCharId, rightCharId?] stage portraits).
 * x/y: same dialog units as the baked lines (/2.5 = px on the 800x600
 * stage, center origin). small: tiny overlay text.
 */
"use strict";
(function (global) {
  var CUT = global.STORY_CUT || {};
  var PATH_CUT = global.STORY_PATH_CUT || [];

  function L(m, x, y, small) {
    return { m: m, small: !!small, x: x, y: y };
  }

  /* Played once after Primary's regular end cutscene: a small wormhole
     has opened where the main tunnel ends. Unlocks Wormhole X (33). */
  CUT.SmallWormhole = [
    L("Whoa. That was NOT here before.", -220, -120),
    L("What wasn't? Are you sure?", 230, 50),
    L("Positive. This is the end of the tunnel. There was just... wall.", 0, -260),
    L("The Student measured it this morning. It ends here.", -260, 130),
    L("Then what is THAT?", 260, -60),
    L("A wormhole. A small one.", 0, 140),
    L("It is still forming. Look at the edges wobble.", -280, -220),
    L("So... do we go in?", 240, 180),
    L("We map it first. Then we go in.", 0, 300),
    L("Dibs on naming it! Wormhole X!", -120, -320),
  ];

  /* Side Path F end: the Skater's shortcut. */
  CUT.Shortcut = [
    L("Told you! Four minutes faster, easy.", 220, -100),
    L("You counted that? Of course you counted that.", -230, 60),
    L("The Student timed it too. She agrees with me.", 230, -40),
    L("Fine! We will call it your shortcut. Happy?", -80, 220),
    L("Very.", 260, 120),
  ];

  /* Side Path S end: snowed in past Winter. */
  CUT.Snowbound = [
    L("It is so quiet out here.", 0, -200),
    L("Too quiet. Where does this even lead?", -240, 80),
    L("Nowhere yet. That is the best part.", 240, -20),
    L("We keep going until the snow stops?", 0, 240),
    L("We keep going until the map stops being blank.", -60, -300),
  ];

  /* Side Path V end: box halls past Boxes. */
  CUT.Unboxed = [
    L("Who keeps stacking these here?", 220, -140),
    L("The Duplicator. Obviously the Duplicator.", -230, 40),
    L("I resent that! ...It was mostly me.", 40, 220),
    L("Can we get through, please?", -120, -260),
    L("Through, over, around. Boxes are just stairs that moved.", 260, 100),
  ];

  /* Wormhole X start: into the small wormhole. */
  CUT.FunnelRide = [
    L("Remember the plan: together, and no showing off.", -200, -160),
    L("No promises.", 240, 60),
    L("It is smaller than the big ones. Tighter turns.", 0, -280),
    L("Stay in the middle of the funnel and it will carry us.", -250, 120),
    L("And if it doesn't?", 250, -40),
    L("Then we run faster.", 0, 200),
  ];

  /* Wormhole X end: landfall on the other side. */
  CUT.Landfall = [
    L("Everybody in one piece?", -220, -120),
    L("I think so. Where is the tunnel we came from?", 220, 80),
    L("Gone. Or... behind us? The geometry here is wrong.", 0, -240),
    L("Look at the light. We are not in our solar system anymore.", -80, 200),
    L("Then we map it. The Far Shore first.", 200, -40),
  ];

  /* Far Shore end: signals from deeper out. */
  CUT.BeyondTheWormhole = [
    L("The Shore is mapped. Every tile of it.", 200, -160),
    L("Then what is that blinking past the ridge?", -230, 60),
    L("A signal? Out here?", 240, -60),
    L("It repeats every eleven seconds. Something built that.", 0, 240),
    L("The Drift it is. Pack light.", -100, -280),
  ];

  /* Far Drift end: the long way back (to be continued). */
  CUT.TheLongWayBack = [
    L("End of the line. The Drift just... stops.", 0, -220),
    L("So this is the edge of the other side?", -240, 80),
    L("The signal comes from here. But there is nothing here.", 230, -20),
    L("Not nothing. Look down. Footprints.", 0, 180),
    L("Someone crossed over before us. Someone going home.", -60, 300),
    L("Then the way back exists. We just have to find it.", 180, -300),
    L("To be continued...", 0, 40, true),
  ];

  /* Start/end cutscene per custom tunnel (index 30-35). */
  var CUSTOM_PATH_CUT = [
    { start: null, end: "Shortcut" },            /* 30 F */
    { start: null, end: "Snowbound" },           /* 31 S */
    { start: null, end: "Unboxed" },             /* 32 V */
    { start: "FunnelRide", end: "Landfall" },    /* 33 Wormhole X */
    { start: null, end: "BeyondTheWormhole" },   /* 34 Far Shore */
    { start: null, end: "TheLongWayBack" },      /* 35 Far Drift */
  ];
  for (var i = 0; i < CUSTOM_PATH_CUT.length; i++) {
    PATH_CUT[30 + i] = CUSTOM_PATH_CUT[i];
  }

  /* Sequel cutscenes: played once after a tunnel's regular end cutscene. */
  var END_CHAIN = global.STORY_END_CHAIN || {};
  END_CHAIN[0] = "SmallWormhole"; /* end of Primary -> the small wormhole */
  global.STORY_END_CHAIN = END_CHAIN;

  /* Cast per cutscene (character ids from STORY.C): shown as portraits on
     stage, left and right. Inferred from the dialogue (the original tracks
     speakers per line in obfuscated bytecode; the bubble's side highlights
     the nearer portrait). Solo scenes show one centered portrait. */
  var CAST = global.STORY_CAST || {};
  var BAKED_CAST = {
    ABCD: [3, 12],            /* Angel vs Duplicator: Plans A-D */
    AngelVsBunny: [3, 10],
    BoatRide: [13, 2],
    Boring: [7, 2],
    Candy: [1, 2],
    CantWait: [2, 12],
    ChangeTheSubject: [9, 1],
    Conspiracy: [2, 12],
    DontKnockIt: [1, 0],
    Fame: [7, 2],
    FourthCondiment: [9, 12],
    GoldMedal: [2, 14],
    GrandOpening: [8],        /* the Gentleman rehearses alone */
    Inflation: [12, 7],
    Insanity: [0, 12],
    JoinUs: [9, 7],
    MyTurn: [1, 0],
    Naming: [8, 0],
    NiceToMeetYou: [0, 3],
    Obvious: [9, 7],
    OfCourse: [2, 10],
    Orbits: [0, 7],
    PlanetStolen: [7, 0],
    SelfAssembly: [2, 12],
    Sneaking: [2, 3],
    SocraticMethod: [0, 2],
    StopSolvingProblems: [3, 0],
    Superpowers: [3, 7],
    Truancy: [7, 1],
    Wait: [3, 10],
    WormholeInSight: [0, 1],
  };
  var CUSTOM_CAST = {
    SmallWormhole: [0, 7],
    Shortcut: [1, 7],
    Snowbound: [0, 2],
    Unboxed: [12, 0],
    FunnelRide: [0, 7],
    Landfall: [0, 7],
    BeyondTheWormhole: [7, 0],
    TheLongWayBack: [0, 2],
    ComingThrough: [0, 1],   /* Runner + Skater: the map, the jumps */
  };
  var k;
  for (k in BAKED_CAST) CAST[k] = BAKED_CAST[k];
  for (k in CUSTOM_CAST) CAST[k] = CUSTOM_CAST[k];
  global.STORY_CAST = CAST;

  /* Mid-tunnel cutscene triggers: {tun, lvl, cut, unlock?}. When checkpoint
     lvl of tunnel tun is completed, cut plays (once ever), staged on that
     same level. Sources: the scene's staged (path, level) + trigger type in
     the decompiled source (IF_FOLLOWING_LEVEL_REACHED = reaching lvl+1),
     and each path's unlockPath/unlockPoint for start scenes:
       ComingThrough staged primary-9 -> Primary 10, unlocks the Skater.
       AngelVsBunny: Home0 unlocks at Winter-9.
       BoatRide: Home3 unlocks at Home1 completion (single level).
       SelfAssembly: NewlyFormed unlocks at Dark-15. */
  var MID_CUTS = global.STORY_MID_CUTS || [
    { tun: 0, lvl: 9, cut: "ComingThrough", skater: true },
    { tun: 12, lvl: 8, cut: "AngelVsBunny", unlock: 1 },
    { tun: 2, lvl: 0, cut: "BoatRide", unlock: 4 },
    { tun: 13, lvl: 14, cut: "SelfAssembly", unlock: 24 },
  ];
  global.STORY_MID_CUTS = MID_CUTS;
  /* PlanetStolen is NOT here: the original unlocks it via achievements
     (8 earned). app.js queues it at the next level end once eligible. */

  /* Replay stage per cutscene (tunnel + level for the S_CUT backdrop).
     end:true resolves to the tunnel's last level at replay time. */
  var STAGE = global.STORY_STAGE || {};
  var i, pc = global.STORY_PATH_CUT || [];
  for (i = 0; i < pc.length; i++) {
    if (pc[i] && pc[i].end && !STAGE[pc[i].end]) STAGE[pc[i].end] = { tun: i, end: true };
    if (pc[i] && pc[i].start && !STAGE[pc[i].start]) STAGE[pc[i].start] = { tun: i, lvl: 0 };
  }
  MID_CUTS.forEach(function (m) { STAGE[m.cut] = { tun: m.tun, lvl: m.lvl }; });
  var chain = global.STORY_END_CHAIN || {};
  Object.keys(chain).forEach(function (t) {
    if (!STAGE[chain[t]]) STAGE[chain[t]] = { tun: +t, end: true };
  });
  global.STORY_STAGE = STAGE;

  global.STORY_CUT = CUT;
  global.STORY_PATH_CUT = PATH_CUT;
})(typeof window !== "undefined" ? window : globalThis);
