/* custom_cutscenes.js - original dialogue for the custom extended tunnels,
 * plus curated per-cutscene CAST tables (custom + original).
 * Companion to cutscenes.js (which is generated by bake_cutscenes.py from
 * the decompiled SWF — do not put custom content there or the next rebake
 * wipes it). Loaded after cutscenes.js, before app.js. Merges into
 * window.STORY_CUT, extends window.STORY_PATH_CUT to ids 30-35, and adds
 * window.STORY_END_CHAIN (tunnel id -> sequel cutscene played once after
 * the tunnel's regular end cutscene) and window.STORY_CAST
 * (cutscene name -> [leftCharId, rightCharId?] stage portraits).
 * x/y: same dialog units as the baked lines (/2.5 = px on the 800x600
 * stage, center origin). small: tiny overlay text.
 */
"use strict";
(function (global) {
  var CUT = global.STORY_CUT || {};
  var PATH_CUT = global.STORY_PATH_CUT || [];

  function L(m, x, y, small) {
    return { m: m, small: !!small, x: x, y: y };
  }

  /* Played once after Primary's regular end cutscene: a small wormhole
     has opened where the main tunnel ends. Unlocks Wormhole X (33). */
  CUT.SmallWormhole = [
    L("Whoa. That was NOT here before.", -220, -120),
    L("What wasn't? Are you sure?", 230, 50),
    L("Positive. This is the end of the tunnel. There was just... wall.", 0, -260),
    L("The Student measured it this morning. It ends here.", -260, 130),
    L("Then what is THAT?", 260, -60),
    L("A wormhole. A small one.", 0, 140),
    L("It is still forming. Look at the edges wobble.", -280, -220),
    L("So... do we go in?", 240, 180),
    L("We map it first. Then we go in.", 0, 300),
    L("Dibs on naming it! Wormhole X!", -120, -320),
  ];

  /* Side Path F end: the Skater's shortcut. */
  CUT.Shortcut = [
    L("Told you! Four minutes faster, easy.", 220, -100),
    L("You counted that? Of course you counted that.", -230, 60),
    L("The Student timed it too. She agrees with me.", 230, -40),
    L("Fine! We will call it your shortcut. Happy?", -80, 220),
    L("Very.", 260, 120),
  ];

  /* Side Path S end: snowed in past Winter. */
  CUT.Snowbound = [
    L("It is so quiet out here.", 0, -200),
    L("Too quiet. Where does this even lead?", -240, 80),
    L("Nowhere yet. That is the best part.", 240, -20),
    L("We keep going until the snow stops?", 0, 240),
    L("We keep going until the map stops being blank.", -60, -300),
  ];

  /* Side Path V end: box halls past Boxes. */
  CUT.Unboxed = [
    L("Who keeps stacking these here?", 220, -140),
    L("The Duplicator. Obviously the Duplicator.", -230, 40),
    L("I resent that! ...It was mostly me.", 40, 220),
    L("Can we get through, please?", -120, -260),
    L("Through, over, around. Boxes are just stairs that moved.", 260, 100),
  ];

  /* Wormhole X start: into the small wormhole. */
  CUT.FunnelRide = [
    L("Remember the plan: together, and no showing off.", -200, -160),
    L("No promises.", 240, 60),
    L("It is smaller than the big ones. Tighter turns.", 0, -280),
    L("Stay in the middle of the funnel and it will carry us.", -250, 120),
    L("And if it doesn't?", 250, -40),
    L("Then we run faster.", 0, 200),
  ];

  /* Wormhole X end: landfall on the other side. */
  CUT.Landfall = [
    L("Everybody in one piece?", -220, -120),
    L("I think so. Where is the tunnel we came from?", 220, 80),
    L("Gone. Or... behind us? The geometry here is wrong.", 0, -240),
    L("Look at the light. We are not in our solar system anymore.", -80, 200),
    L("Then we map it. The Far Shore first.", 200, -40),
  ];

  /* Far Shore end: signals from deeper out. */
  CUT.BeyondTheWormhole = [
    L("The Shore is mapped. Every tile of it.", 200, -160),
    L("Then what is that blinking past the ridge?", -230, 60),
    L("A signal? Out here?", 240, -60),
    L("It repeats every eleven seconds. Something built that.", 0, 240),
    L("The Drift it is. Pack light.", -100, -280),
  ];

  /* Far Drift end: the long way back (to be continued). */
  CUT.TheLongWayBack = [
    L("End of the line. The Drift just... stops.", 0, -220),
    L("So this is the edge of the other side?", -240, 80),
    L("The signal comes from here. But there is nothing here.", 230, -20),
    L("Not nothing. Look down. Footprints.", 0, 180),
    L("Someone crossed over before us. Someone going home.", -60, 300),
    L("Then the way back exists. We just have to find it.", 180, -300),
    L("To be continued...", 0, 40, true),
  ];

  /* ---- the extended-path story: Wormhole X -> Far Shore -> Far Drift,
     told in beats down the 200-checkpoint runs. Each one fires as its
     checkpoint is cleared and stages on that stretch of tunnel. ---- */
  CUT.DeeperIn = [
    L("How long has this funnel been going?", 220, -120),
    L("Long enough that I stopped counting the tiles.", -230, 60),
    L("The map ends behind us. Everything ahead is blank.", 0, -250),
    L("Then we are drawing it as we go.", -120, 190),
    L("Somebody should write this down.", 240, 120),
    L("I AM writing it down!", 0, 300),
  ];
  CUT.TheLongFunnel = [
    L("We should have hit the end by now.", 230, -100),
    L("We did. Three times. It keeps opening back up.", -220, 80),
    L("That is not how tunnels work.", 0, -260),
    L("Nothing here is how tunnels work.", 240, -20),
    L("Keep the lights on and keep moving.", -100, 220),
  ];
  CUT.SomethingMoving = [
    L("Did you see that? Left wall, two rows back.", 220, -140),
    L("See what? There is nothing there.", -230, 40),
    L("Something moved. Same speed as us.", 0, -270),
    L("Then it is pacing us. Do not slow down.", -240, 200),
    L("Was not planning to.", 250, 140),
  ];
  CUT.FarSide = [
    L("The funnel is widening. Look at the walls.", 230, -120),
    L("We are almost through. I can see light.", -220, 80),
    L("That is not light. That is the other side.", 0, -250),
    L("Same thing, out here.", 240, 60),
    L("Everybody ready?", -60, 240),
    L("Ready.", 180, 300),
  ];
  CUT.ShoreParty = [
    L("So this is the Shore.", 0, -200),
    L("It is... calm. I do not trust calm.", -230, 80),
    L("The Student is already taking measurements.", 240, -30),
    L("Let her. It is useful for once.", -60, 230),
    L("I heard that.", 180, -300),
  ];
  CUT.HalfwayToNowhere = [
    L("Halfway. Assuming there is such a thing out here.", 220, -130),
    L("The signal is louder than it was. Steady now.", -230, 60),
    L("Steady is worse than loud.", 240, -40),
    L("Then we do not look at whatever is making it.", -80, 210),
    L("We absolutely look at it.", 200, 270),
  ];
  CUT.TheRidgeLine = [
    L("The ridge line. Past that is the Drift.", 230, -110),
    L("And past the Drift?", -230, 70),
    L("Home, if you believe the footprints.", 0, -260),
    L("I do not believe footprints.", 240, -30),
    L("Then believe the signal. It is still counting.", -80, 220),
  ];
  CUT.Driftwood = [
    L("The Drift is nothing but loose tiles.", 220, -140),
    L("Then we run light. No stopping.", -230, 60),
    L("Stopping is not on the menu.", 240, -20),
    L("The menu is: forward.", 0, -270),
    L("I have never liked that menu.", -100, 220),
  ];
  CUT.CountingDown = [
    L("Eighty and counting. That is where we started.", 230, -120),
    L("And still nothing at the end of it.", -230, 80),
    L("There is no end. That is the point of the Drift.", 0, -260),
    L("Then we make one.", 240, 120),
  ];
  CUT.Footprints = [
    L("There. On the floor. Those are prints.", 220, -140),
    L("Big ones. Bigger than any of us.", -230, 60),
    L("Which means the way back is real.", 0, -260),
    L("The way back is real.", -60, 230),
    L("Then we finish this. All the way to the tail.", 200, 140),
  ];
  /* branch beats */
  CUT.StaticInTheWalls = [
    L("The rift just... stops.", 220, -130),
    L("Same as the funnel. It opens back into the main one.", -230, 60),
    L("Then we are not lost. Good.", 240, -30),
    L("We were never lost. I knew where we were the whole time.", 0, -260),
    L("You did not.", -80, 220),
  ];
  CUT.SayThatAgain = [
    L("...and that is why the walls repeat.", 230, -120),
    L("Why did you say it twice?", -230, 70),
    L("I did not.", 240, -40),
    L("Then the tunnel did. It is still learning.", 0, -250),
    L("Let us leave before it finishes.", -80, 220),
  ];
  CUT.GiveWay = [
    L("The Shoal is behind us. Every tile of it, gone.", 230, -130),
    L("You stepped on one and the whole floor left.", -230, 70),
    L("In my defence, it was a very good step.", 240, -40),
    L("Never do that again.", -80, 220),
  ];
  CUT.OldGrowth = [
    L("That shelf was older than the map.", 220, -120),
    L("Older than the tunnel, probably.", -230, 60),
    L("And we ran straight over it.", 240, -30),
    L("It will grow back. Probably.", 0, -260),
    L("Probably.", -100, 220),
  ];
  CUT.Settling = [
    L("The wake is settling. Whatever made it is ahead.", -230, 60),
    L("How far ahead?", 220, -130),
    L("Close enough that it is still moving.", 0, -260),
    L("Then we are going the right way.", 240, -20),
  ];
  CUT.WarmWalls = [
    L("The walls are warm here. Something burned.", 230, -130),
    L("How long ago?", -230, 70),
    L("Long enough that only the stone remembers.", 0, -260),
    L("Then somebody else got this far.", 240, -30),
    L("Somebody else got this far and did not come back.", -80, 220),
  ];

  /* ---- the recovered original paths (42-45): the home planet's two plan
     runs and the P wormhole with its crossing. Real levels that ship in the
     game but that the explore map never linked in, so the cast gets to find
     them. ---- */
  CUT.BelowTheHouse = [
    L("Under the house. There is a whole tunnel under the house.", 220, -140),
    L("It was on the survey. Just not on any map anyone drew.", -230, 60),
    L("So we are the first ones down here?", 240, -30),
    L("Unless somebody built it and left. Look at the tiles.", 0, -260),
    L("They are clean. Nobody has run these.", -120, 190),
    L("Then we have some runs to give it.", 180, 120),
  ];
  CUT.PlanARecorded = [
    L("Sixteen checkpoints. Plan A is on the map now.", 230, -120),
    L("It was always there. We just had not walked it.", -230, 70),
    L("Writing it down counts.", 240, -40),
    L("Then write down the other one too.", 0, -260),
    L("The other one?", -80, 220),
  ];
  CUT.PlanCUnlisted = [
    L("These walls do not match the plan.", 220, -130),
    L("Which plan?", -230, 60),
    L("Any of them. The survey says this is a straight run.", 0, -260),
    L("It is not straight.", 240, -30),
    L("Nothing on this planet is straight.", -120, 200),
  ];
  CUT.PlanCMapped = [
    L("Twenty-two checkpoints. Plan C, end to end.", 0, -230),
    L("Both plan runs, walked and recorded.", -230, 80),
    L("Somebody owes me a better map.", 240, -20),
    L("Somebody just made one.", 240, 200),
    L("Fair.", -120, -280),
  ];
  CUT.HushInP = [
    L("Wormhole P. Why does nobody talk about this one?", 220, -130),
    L("Because it is quiet. Listen.", -230, 60),
    L("...nothing. No hum, no drift.", 240, -30),
    L("That is what worries me.", 0, -260),
    L("Then do not stop in it.", -100, 220),
  ];
  CUT.WormholeSkipped = [
    L("Every wormhole we know has a letter. This one skipped the list.", 230, -130),
    L("It still has a mouth and an end. Same as the rest.", -230, 70),
    L("Ten checkpoints, then the crossing.", 0, -260),
    L("The crossing of what?", 240, -20),
    L("Of P, presumably. Keep moving.", -80, 220),
  ];
  CUT.TheCrossingAhead = [
    L("P is behind us. The crossing is through there.", 220, -130),
    L("That is not a tunnel mouth. That is a seam.", -230, 60),
    L("Two tunnels meeting. That is all a seam is.", 0, -260),
    L("Nobody has ever run one.", 240, -30),
    L("Nobody has ever found one, either. Go.", -100, 220),
  ];
  CUT.CrossedOver = [
    L("That was a crossing. We went through a crossing.", 0, -230),
    L("And came out the other side of a tunnel we were not in.", -230, 80),
    L("Which means the two tunnels are the same tunnel.", 230, -30),
    L("Out here? Probably.", 0, 200),
    L("Then we add it to the map and never explain it.", 200, -280),
  ];

  /* Start/end cutscene per custom tunnel (index 30-35). */
  var CUSTOM_PATH_CUT = [
    { start: null, end: "Shortcut" },            /* 30 F */
    { start: null, end: "Snowbound" },           /* 31 S */
    { start: null, end: "Unboxed" },             /* 32 V */
    { start: "FunnelRide", end: "Landfall" },    /* 33 Wormhole X */
    { start: null, end: "BeyondTheWormhole" },   /* 34 Far Shore */
    { start: null, end: "TheLongWayBack" },      /* 35 Far Drift */
  ];
  for (var i = 0; i < CUSTOM_PATH_CUT.length; i++) {
    PATH_CUT[30 + i] = CUSTOM_PATH_CUT[i];
  }

  /* Recovered original paths (42-45), in tunnel id order. */
  var RECOVERED_PATH_CUT = [
    { start: "BelowTheHouse", end: "PlanARecorded" },      /* 42 Home Plan A */
    { start: null, end: "PlanCMapped" },                   /* 43 Home Plan C */
    { start: "WormholeSkipped", end: "TheCrossingAhead" }, /* 44 Wormhole P */
    { start: null, end: "CrossedOver" },                   /* 45 the Crossing */
  ];
  for (var r = 0; r < RECOVERED_PATH_CUT.length; r++) {
    PATH_CUT[42 + r] = RECOVERED_PATH_CUT[r];
  }

  /* Sequel cutscenes: played once after a tunnel's regular end cutscene. */
  var END_CHAIN = global.STORY_END_CHAIN || {};
  END_CHAIN[0] = "SmallWormhole"; /* end of Primary -> the small wormhole */
  global.STORY_END_CHAIN = END_CHAIN;

  /* Cast per cutscene (character ids from STORY.C): shown as portraits on
     stage, left and right. Inferred from the dialogue (the original tracks
     speakers per line in obfuscated bytecode; the bubble's side highlights
     the nearer portrait). Solo scenes show one centered portrait. */
  var CAST = global.STORY_CAST || {};
  var BAKED_CAST = {
    ABCD: [3, 12],            /* Angel vs Duplicator: Plans A-D */
    AngelVsBunny: [3, 10],
    BoatRide: [13, 2],
    Boring: [7, 2],
    Candy: [1, 2],
    CantWait: [2, 12],
    ChangeTheSubject: [9, 1],
    Conspiracy: [2, 12],
    DontKnockIt: [1, 0],
    Fame: [7, 2],
    FourthCondiment: [9, 12],
    GoldMedal: [2, 14],
    GrandOpening: [8],        /* the Gentleman rehearses alone */
    Inflation: [12, 7],
    Insanity: [0, 12],
    JoinUs: [9, 7],
    MyTurn: [1, 0],
    Naming: [8, 0],
    NiceToMeetYou: [0, 3],
    Obvious: [9, 7],
    OfCourse: [2, 10],
    Orbits: [0, 7],
    PlanetStolen: [7, 0],
    SelfAssembly: [2, 12],
    Sneaking: [2, 3],
    SocraticMethod: [0, 2],
    StopSolvingProblems: [3, 0],
    Superpowers: [3, 7],
    Truancy: [7, 1],
    Wait: [3, 10],
    WormholeInSight: [0, 1],
  };
  var CUSTOM_CAST = {
    SmallWormhole: [0, 7],
    Shortcut: [1, 7],
    Snowbound: [0, 2],
    Unboxed: [12, 0],
    FunnelRide: [0, 7],
    Landfall: [0, 7],
    BeyondTheWormhole: [7, 0],
    TheLongWayBack: [0, 2],
    DeeperIn: [0, 7],
    TheLongFunnel: [0, 2],
    SomethingMoving: [7, 0],
    FarSide: [0, 1],
    ShoreParty: [7, 0],
    HalfwayToNowhere: [0, 7],
    TheRidgeLine: [0, 2],
    Driftwood: [2, 0],
    CountingDown: [0, 7],
    Footprints: [0, 2],
    StaticInTheWalls: [1, 0],
    SayThatAgain: [0, 7],
    GiveWay: [2, 0],
    OldGrowth: [7, 0],
    Settling: [0, 2],
    WarmWalls: [0, 7],
    ComingThrough: [0, 1],   /* Runner + Skater: the map, the jumps */
    BelowTheHouse: [0, 7],
    PlanARecorded: [7, 0],
    PlanCUnlisted: [7, 12],
    PlanCMapped: [0, 7],
    HushInP: [0, 7],
    WormholeSkipped: [0, 1],
    TheCrossingAhead: [1, 0],
    CrossedOver: [0, 7],
  };
  var k;
  for (k in BAKED_CAST) CAST[k] = BAKED_CAST[k];
  for (k in CUSTOM_CAST) CAST[k] = CUSTOM_CAST[k];
  global.STORY_CAST = CAST;

  /* Mid-tunnel cutscene triggers: {tun, lvl, cut, unlock?}. When checkpoint
     lvl of tunnel tun is completed, cut plays (once ever), staged on that
     same level. Sources: the scene's staged (path, level) + trigger type in
     the decompiled source (IF_FOLLOWING_LEVEL_REACHED = reaching lvl+1),
     and each path's unlockPath/unlockPoint for start scenes:
       ComingThrough staged primary-9 -> Primary 10, unlocks the Skater.
       AngelVsBunny: Home0 unlocks at Winter-9.
       BoatRide: Home3 unlocks at Home1 completion (single level).
       SelfAssembly: NewlyFormed unlocks at Dark-15. */
  var MID_CUTS = global.STORY_MID_CUTS || [
    { tun: 0, lvl: 9, cut: "ComingThrough", skater: true },
    { tun: 12, lvl: 8, cut: "AngelVsBunny", unlock: 1 },
    { tun: 2, lvl: 0, cut: "BoatRide", unlock: 4 },
    { tun: 13, lvl: 14, cut: "SelfAssembly", unlock: 24 },
    /* the extended path, beat by beat down its long runs and out along the
       branches. Milestones sit roughly a quarter of a run apart so the story
       keeps pace with 200 checkpoints. */
    { tun: 33, lvl: 24, cut: "DeeperIn" },
    { tun: 33, lvl: 55, cut: "TheLongFunnel" },
    { tun: 33, lvl: 90, cut: "SomethingMoving" },
    { tun: 33, lvl: 120, cut: "FarSide" },
    { tun: 34, lvl: 30, cut: "ShoreParty" },
    { tun: 34, lvl: 70, cut: "HalfwayToNowhere" },
    { tun: 34, lvl: 110, cut: "TheRidgeLine" },
    { tun: 35, lvl: 40, cut: "Driftwood" },
    { tun: 35, lvl: 80, cut: "CountingDown" },
    { tun: 35, lvl: 120, cut: "Footprints" },
    { tun: 36, lvl: 29, cut: "StaticInTheWalls" },
    { tun: 37, lvl: 29, cut: "SayThatAgain" },
    { tun: 38, lvl: 29, cut: "GiveWay" },
    { tun: 39, lvl: 29, cut: "OldGrowth" },
    { tun: 40, lvl: 29, cut: "Settling" },
    { tun: 41, lvl: 29, cut: "WarmWalls" },
    /* recovered original paths */
    { tun: 43, lvl: 10, cut: "PlanCUnlisted" },
    { tun: 44, lvl: 4, cut: "HushInP" },
  ];
  global.STORY_MID_CUTS = MID_CUTS;
  /* PlanetStolen is NOT here: the original unlocks it via achievements
     (8 earned). app.js queues it at the next level end once eligible. */

  /* Replay stage per cutscene (tunnel + level for the S_CUT backdrop).
     end:true resolves to the tunnel's last level at replay time.
     at: "start" means the scene really plays at the tunnel's opening, so the
     backdrop is that level's head; "end" (the default) means the scene plays
     as a checkpoint is completed, so the backdrop is that level's TAIL —
     staging it at the level head would show the wrong stretch of tunnel and
     the wrong camera angle. */
  var STAGE = global.STORY_STAGE || {};
  var i, pc = global.STORY_PATH_CUT || [];
  for (i = 0; i < pc.length; i++) {
    if (pc[i] && pc[i].end && !STAGE[pc[i].end]) STAGE[pc[i].end] = { tun: i, end: true, at: "end" };
    if (pc[i] && pc[i].start && !STAGE[pc[i].start]) STAGE[pc[i].start] = { tun: i, lvl: 0, at: "start" };
  }
  MID_CUTS.forEach(function (m) { STAGE[m.cut] = { tun: m.tun, lvl: m.lvl, at: "end" }; });
  var chain = global.STORY_END_CHAIN || {};
  Object.keys(chain).forEach(function (t) {
    if (!STAGE[chain[t]]) STAGE[chain[t]] = { tun: +t, end: true, at: "end" };
  });
  global.STORY_STAGE = STAGE;

  global.STORY_CUT = CUT;
  global.STORY_PATH_CUT = PATH_CUT;
})(typeof window !== "undefined" ? window : globalThis);
