#!/usr/bin/env python3
"""Bake map background + decorations into assets_data.h for WASM rendering.

Scales the original Run 3 mapmask and decoration images to fit the WxH canvas
(1280x720, stretched to cover whole screen, not tiled).
Also generates the C arrays for tunnel node positions (scaled from the original
1550x1100 coordinate space to WxH).
"""
from PIL import Image
import json
import os

W, H = 1280, 720  # canvas size — 2x 640x360 for higher framebuffer resolution, covers full page
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS_DIR = os.path.join(BASE, "assets")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "map_assets.h")


def image_to_rgba(im):
    w, h = im.size
    pixels = list(im.getdata())
    data = []
    for r, g, b, a in pixels:
        data.append((a << 24) | (r << 16) | (g << 8) | b)
    return w, h, data


def write_frame_array(f, name, w, h, data):
    f.write(f"static const uint32_t {name}[] = {{\n")
    for y in range(h):
        f.write("  ")
        for x in range(w):
            f.write(f"0x{data[y * w + x]:08X},")
        f.write("\n")
    f.write("};\n")


os.makedirs(os.path.dirname(OUT), exist_ok=True)

# Map transform: UNIFORM scale of the original map space so the layout keeps its
# shape (non-uniform SX/SY would shear it). S=0.82 fits y (-72..660) with room.
MSX, MSY = 0.82, 0.82
MOX, MOY = 150, 100
SX, SY = MSX, MSY  # legacy names used below


def map_sxy(ox, oy):
    """Original map coords -> screen coords (rounded, always >= 0 here)."""
    import math
    return (int(math.floor(ox * MSX + MOX + 0.5)),
            int(math.floor(oy * MSY + MOY + 0.5)))

total_bytes = 0

with open(OUT, "w") as f:
    f.write("/* map_assets.h - baked map background + decorations for WASM rendering.\n")
    f.write(" * Generated by bake_map.py. Do not edit manually. */\n")
    f.write("#ifndef MAP_ASSETS_H\n#define MAP_ASSETS_H\n\n")
    f.write("#include <stdint.h>\n\n")

    # ===== MAP BACKGROUND =====
    # Use map_mapiconflat.png (brown parchment) tiled, then overlay map_mapmask.png (dotted map)
    flat_path = os.path.join(ASSETS_DIR, "images/map_mapiconflat.png")
    mask_path = os.path.join(ASSETS_DIR, "images/map_mapmask.png")

    canvas = Image.new("RGBA", (W, H), (180, 150, 110, 255))  # fallback brown

    if os.path.exists(flat_path):
        flat = Image.open(flat_path).convert("RGBA").resize((W, H), Image.LANCZOS)
        # stretch to cover whole canvas — no tiling
        canvas = flat
        print(f"  stretched map_mapiconflat to {W}x{H}")

    if os.path.exists(mask_path):
        mask = Image.open(mask_path).convert("RGBA")
        # resize mask to canvas size
        mask = mask.resize((W, H), Image.LANCZOS)
        # composite: mask on top of flat background
        canvas = Image.alpha_composite(canvas, mask)
        print(f"  overlaid map_mapmask: {W}x{H}")

    w, h, data = image_to_rgba(canvas)
    write_frame_array(f, "map_bg", w, h, data)
    f.write(f"#define MAP_BG_W {w}\n")
    f.write(f"#define MAP_BG_H {h}\n\n")
    total_bytes += w * h * 4
    print(f"  map_bg final: {w}x{h}")

    # ===== DECORATION IMAGES =====
    # sizes doubled for 1280x720 (2x) to keep visual proportion
    DECORATIONS = [
        ("deco_planet",     "images/map_planet.png",           96, 96),
        ("deco_teapot",     "images/map_teapot.png",           56, 56),
        ("deco_wormhole",   "images/map_wormhole.png",         72, 72),
        ("deco_snowflakes", "images/map_snowflakes.png",       48, 48),
        ("deco_bridge",     "images/map_bridge.png",            56, 40),
        ("deco_box",        "images/map_box.png",               40, 40),
        ("deco_movbox",     "images/map_movableboxicon.png",    32, 32),
        ("deco_speech",     "images/map_speechbubbles.png",     40, 40),
        ("deco_infinity",   "images/map_infinity.png",          64, 48),
        ("deco_battery",    "images/map_battery.png",           40, 40),
        ("deco_belt0",      "images/map_planetoidbelt0.png",    72, 72),
        ("deco_belt1",      "images/map_planetoidbelt1.png",    56, 56),
        ("deco_run3logo",   "images/menu_run3.png",            360, 112),
    ]

    deco_entries = []
    for dname, drel, dw, dh in DECORATIONS:
        dpath = os.path.join(ASSETS_DIR, drel)
        if not os.path.exists(dpath):
            print(f"  {dname}: NOT FOUND")
            continue
        dim = Image.open(dpath).convert("RGBA")
        dim = dim.resize((dw, dh), Image.LANCZOS)
        w, h, data = image_to_rgba(dim)
        write_frame_array(f, dname, w, h, data)
        f.write(f"#define {dname}_W {w}\n")
        f.write(f"#define {dname}_H {h}\n\n")
        total_bytes += w * h * 4
        print(f"  {dname}: {w}x{h}")
        deco_entries.append(dname)

    # Decoration positions (from story.js MAP_DECOR, scaled to WxH)
    DECOR_POSITIONS = [
        ("deco_planet",     1450, 50),
        ("deco_teapot",     720, 310),
        ("deco_wormhole",   1180, 390),
        ("deco_snowflakes", 100, 100),
        ("deco_bridge",     1100, 230),
        ("deco_box",        1145, 290),
        ("deco_movbox",     1130, 240),
        ("deco_speech",     580, 50),
        ("deco_infinity",   575, 970),
        ("deco_battery",    1070, 100),
        ("deco_belt0",      300, 130),
        ("deco_belt1",      850, 160),
    ]

    f.write("/* Decoration struct */\n")
    f.write("typedef struct {\n")
    f.write("  const uint32_t *pix;\n")
    f.write("  int w, h, x, y;\n")
    f.write("} map_deco_t;\n\n")

    f.write(f"#define MAP_DECO_COUNT {len(DECOR_POSITIONS)}\n\n")

    f.write("static const map_deco_t map_decorations[] = {\n")
    for dname, ox, oy in DECOR_POSITIONS:
        if dname in deco_entries:
            cx, cy = map_sxy(ox, oy)
            f.write(f"  {{ {dname}, {dname}_W, {dname}_H, {cx}, {cy} }},\n")
    f.write("};\n\n")

    # ===== TUNNEL NODE POSITIONS =====
    # ===== TUNNEL NODES: first waypoints straight from the original map =====
    # (orig_map.json, vendored from the decompiled SWF's mapcontents).
    # Format: id, kind(0=name,1=letter), x, y, r, g, b — x/y MUST match the
    # path's first waypoint (asserted below) and story.js T[] positions.
    # Colors/kind are our display layer.
    TUNNELS_DATA = [
        # id, kind, x, y, r, g, b
        (0,  0, 0, 0,         125,211,252),   # Primary
        (1,  0, 400, 420,     147,197,253),   # Home 0
        (2,  0, 290, 315,     147,197,253),   # Home 1
        (3,  0, 290, 315,     147,197,253),   # Home 2
        (4,  0, 62, 314,      147,197,253),   # Home 3
        (5,  1, 1796, 0,       94,234,212),   # A
        (6,  1, 1440, 264,    252,211,77),    # B
        (7,  1, 1285, 637,    134,239,172),   # D
        (8,  1, 1817, 306,    216,180,254),   # G
        (9,  1, 2040, 324,    196,181,253),   # L
        (10, 1, 1200, 240,    240,171,252),   # M
        (11, 1, 2160, 394,    251,146,60),    # T
        (12, 0, 540, 138,     191,219,254),   # Winter
        (13, 0, 1000, 212,     30,27,75),     # Dark
        (14, 0, 1200, 240,    167,139,250),   # Boxes
        (15, 0, 1016, 47,      96,165,250),   # Memory
        (16, 0, 940, 404,     103,232,249),   # River
        (17, 1, 2476, 103,    192,132,252),   # Wormhole C
        (18, 1, 2509, 250,    192,132,252),   # Wormhole H
        (19, 1, 2476, -14,    192,132,252),   # Wormhole I
        (20, 1, 3021, 219,    192,132,252),   # Wormhole J
        (21, 1, 2767, 188,    192,132,252),   # Wormhole K
        (22, 1, 2180, -40,    192,132,252),   # Wormhole N
        (23, 1, 2950, 89,     192,132,252),   # Wormhole Space
        (24, 0, 672, -22,      52,211,153),   # Newly Formed
        (25, 0, 3327, 204,    251,191,36),    # Runway 0
        (26, 0, 3784, 310,    251,191,36),    # Runway 1
        (27, 0, 1305, 133,     45,212,191),   # Coordination
        (28, 1, 1440, 264,    167,139,250),   # U
        (29, 1, 400, 420,      52,211,153),   # W
    ]

    import json as _json
    _omap = _json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                         "orig_map.json")))
    _wp_by_id = {t['id']: t['waypoints'] for t in _omap['tunnels']}
    assert sorted(_wp_by_id) == list(range(30)), "orig_map.json must hold ids 0-29"

    f.write("/* Tunnel node data: id, kind(0=name,1=letter), x, y, r, g, b.\n")
    f.write(" * Node coords = original first waypoints (uniform map transform). */\n")
    f.write("#define MAP_TUNNEL_COUNT 30\n\n")

    f.write("typedef struct {\n")
    f.write("  int16_t x, y;\n")
    f.write("  uint8_t r, g, b;\n")
    f.write("  uint8_t kind; /* 0=name, 1=letter */\n")
    f.write("} map_node_t;\n\n")

    f.write("static const map_node_t map_nodes[MAP_TUNNEL_COUNT] = {\n")
    for tid, kind, ox, oy, r, g, b in TUNNELS_DATA:
        # node MUST equal the path's first waypoint (original layout guarantee)
        w0 = _wp_by_id[tid][0]
        assert map_sxy(w0[0], w0[1]) == map_sxy(ox, oy), f"node {tid} != first waypoint"
        cx, cy = map_sxy(ox, oy)
        f.write(f"  {{ {cx}, {cy}, {r}, {g}, {b}, {kind} }}, /* {tid} */\n")
    f.write("};\n\n")

    # ===== PATH POLYLINES: the original drawn curves (screen coords) =====
    # Checkpoints are spaced evenly along these; the map draws them as-is.
    f.write("/* Path polylines: x0,y0,x1,y1,... per tunnel (screen coords). */\n")
    for tid, kind, ox, oy, r, g, b in TUNNELS_DATA:
        pts = []
        for wx, wy in _wp_by_id[tid]:
            cx, cy = map_sxy(wx, wy)
            pts.append(f"{cx},{cy}")
        f.write(f"static const int16_t map_wp_{tid}[] = {{{','.join(pts)}}};\n")
    f.write("static const int16_t *map_wp[MAP_TUNNEL_COUNT] = {\n")
    for tid, kind, ox, oy, r, g, b in TUNNELS_DATA:
        f.write(f"  map_wp_{tid},\n")
    f.write("};\n")
    f.write("static const uint8_t map_wp_n[MAP_TUNNEL_COUNT] = {\n")
    for tid, kind, ox, oy, r, g, b in TUNNELS_DATA:
        n = len(_wp_by_id[tid])
        assert 2 <= n <= 255, f"path {tid} waypoint count {n}"
        f.write(f"  {n}, /* {tid} */\n")
    f.write("};\n\n")

    # ===== TUNNEL NAMES (short, for display) — ids 0-29 only =====
    NAMES = [
        "Primary", "Home 0", "Home 1", "Home 2", "Home 3",
        "A", "B", "D", "G", "L", "M", "T",
        "Winter", "Dark", "Boxes", "Memory", "River",
        "WH C", "WH H", "WH I", "WH J", "WH K", "WH N", "WH Spc",
        "Newly", "Runway0", "Runway1", "Coord",
        "U", "W",
    ]
    assert len(NAMES) == len(TUNNELS_DATA) == 30

    f.write("/* Tunnel name strings */\n")
    f.write("static const char *map_tunnel_names[MAP_TUNNEL_COUNT] = {\n")
    for i, name in enumerate(NAMES):
        f.write(f'  "{name}", /* {i} */\n')
    f.write("};\n\n")

    f.write("#endif /* MAP_ASSETS_H */\n")

print(f"\nTotal map assets: {total_bytes} bytes ({total_bytes/1024:.0f} KB)")
print(f"Done: {OUT}")
