#!/usr/bin/env python3
"""Bake a bitmap font atlas into C arrays for WASM text rendering.

Renders ASCII 32-126 using the Comfortaa font at a small pixel size,
then packs all glyphs into a texture atlas with metadata.
"""
from PIL import Image, ImageDraw, ImageFont
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "font_data.h")
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_PATH = os.path.join(BASE, "assets/fonts/comfortaa.ttf")

GLYPH_W, GLYPH_H = 38, 52  # max glyph size — ~2x for 720p, crisp at larger sizes
FONT_SIZE = 48
FIRST_CHAR = 32  # space
NUM_CHARS = 95    # 32..126

os.makedirs(os.path.dirname(OUT), exist_ok=True)

# Load font
try:
    font = ImageFont.truetype(FONT_PATH, FONT_SIZE)
except:
    font = ImageFont.load_default()
    print("WARNING: could not load Comfortaa, using default font")

# Get font metrics for baseline alignment
try:
    ascent, descent = font.getmetrics()
except:
    ascent, descent = (FONT_SIZE * 0.8, FONT_SIZE * 0.2)
    print(f"WARNING: getmetrics failed, using {ascent},{descent}")

# Measure each glyph — store bbox and y bearing for baseline alignment
# Use a common baseline for all glyphs: yoff = ascent (distance top of cell to baseline)
# This makes all glyphs rest on the same line, with descenders (ygpq) correctly below
glyphs = []
for i in range(NUM_CHARS):
    ch = chr(FIRST_CHAR + i)
    bbox = font.getbbox(ch)
    bbox_lb = font.getbbox(ch, anchor='lb')
    gw = bbox[2] - bbox[0]
    gh = bbox[3] - bbox[1]
    if gw < 1: gw = 1
    if gh < 1: gh = 1
    if gw > GLYPH_W: gw = GLYPH_W
    if gh > GLYPH_H: gh = GLYPH_H
    # y bearing: distance from top of ink to baseline — yoff = ascent - bbox_top
    # This makes all glyphs rest on the same baseline, with descenders (ygpq) correctly below
    yoff = ascent - bbox[1]
    # clamp to sensible range
    if yoff < 0: yoff = 0
    if yoff > GLYPH_H: yoff = GLYPH_H
    glyphs.append((ch, gw, gh, bbox, bbox_lb, yoff))

# Pack glyphs into rows (fixed-height atlas)
atlas_w = 0
rows = []
row = []
row_h = 0
for i, (ch, gw, gh, bbox, bbox_lb, yoff) in enumerate(glyphs):
    if row and atlas_w + gw > 1024:
        rows.append((row, row_h))
        row = []
        atlas_w = 0
        row_h = 0
    row.append((i, ch, gw, gh, bbox, bbox_lb, yoff, atlas_w))
    atlas_w += gw + 1
    if gh > row_h:
        row_h = gh
if row:
    rows.append((row, row_h))

atlas_h = sum(rh for _, rh in rows)
total_w = max(sum(gw + 1 for _, _, gw, _, _, _, _, _ in r) for r, _ in rows)

# Render atlas
atlas = Image.new("RGBA", (total_w, atlas_h), (0, 0, 0, 0))
draw = ImageDraw.Draw(atlas)

glyph_meta = []  # (char_index, x, y, w, h, yoff)
for row_items, rh in rows:
    y_off = sum(rh2 for _, rh2 in rows[:rows.index((row_items, rh))])
    x_off = 0
    for idx, ch, gw, gh, bbox, bbox_lb, yoff, _ in row_items:
        # draw character offset by -bbox to align ink at x_off,y_off (fixes UVs)
        draw.text((x_off - bbox[0], y_off - bbox[1]), ch, fill=(255, 255, 255, 255), font=font)
        glyph_meta.append((FIRST_CHAR + idx, x_off, y_off, gw, gh, yoff))
        x_off += gw + 1

# Write C header
with open(OUT, "w") as f:
    f.write("/* font_data.h - baked bitmap font atlas for WASM text rendering.\n")
    f.write(" * Generated by bake_font.py. Do not edit manually. */\n")
    f.write("#ifndef FONT_DATA_H\n#define FONT_DATA_H\n\n")
    f.write("#include <stdint.h>\n\n")

    f.write(f"#define FONT_ATLAS_W {total_w}\n")
    f.write(f"#define FONT_ATLAS_H {atlas_h}\n")
    f.write(f"#define FONT_GLYPH_W {GLYPH_W}\n")
    f.write(f"#define FONT_GLYPH_H {GLYPH_H}\n")
    f.write(f"#define FONT_FIRST_CHAR {FIRST_CHAR}\n")
    f.write(f"#define FONT_NUM_CHARS {NUM_CHARS}\n\n")

    # Atlas pixels
    f.write("static const uint32_t font_atlas[] = {\n")
    for y in range(atlas_h):
        f.write("  ")
        for x in range(total_w):
            r, g, b, a = atlas.getpixel((x, y))
            f.write(f"0x{(a << 24) | (r << 16) | (g << 8) | b:08X},")
        f.write("\n")
    f.write("};\n\n")

    # Glyph metadata: char_index, x, y, w, h, yoff (baseline offset)
    f.write("typedef struct { int x, y, w, h, yoff; } glyph_t;\n\n")
    f.write("static const glyph_t font_glyphs[FONT_NUM_CHARS] = {\n")
    for ci, gx, gy, gw, gh, yoff in glyph_meta:
        f.write(f"  {{ {gx}, {gy}, {gw}, {gh}, {yoff} }}, /* '{chr(ci)}' ({ci}) */\n")
    f.write("};\n\n")

    f.write("#endif /* FONT_DATA_H */\n")

atlas.save(os.path.join(os.path.dirname(OUT), "font_preview.png"))
print(f"Atlas: {total_w}x{atlas_h}, {len(glyph_meta)} glyphs")
print(f"Done: {OUT}")
