#!/usr/bin/env python3
"""Bake the world map's art and coordinates into map_assets.h.

THE COORDINATE SPACE IS THE 2014 BUILD'S OWN, and the placement rule is its
too (MapMenu.create):

  * ScaledAssets is built as `new §--____-___-§(3000, 2000, true, null)`, so
    the map's design box is 3000 x 2000 and every COORDINATE is scaled by
    `k = min(stageW/3000, stageH/2000)` (the `true` is the uniform flag).
  * `ScaledAssets.§---_--_§()` (the Bitmap loader) sets that Bitmap's scale to
    TWICE k, so every BITMAP — the MapMask and every decoration — is drawn at
    2k, i.e. at its native pixel size x 2k.
  * MapMask.png is placed at `x = (stageW - width)/2`, `y = stageH - height`
    with width/height its SCALED size (3072k x 2048k), and the content pane
    sits at that box's top-left + 1: that is design (0, 0).

So this bake stores the map in DESIGN UNITS and lets the renderer apply k,
which is the only way the rule can hold at every window: k is 0.16 at a 480-wide
base box and 0.36 at a 1280-wide one.

The vendored orig_map.json holds the v1.13 MapContents.json verbatim, and the
v1.13's coordinates are the 2014's divided by 2.5 (checked: `explore` starts
(0,0),(1200,300) in the 2014 and (0,0),(480,120) in the v1.13; the Teapot,
Snowflakes and DerpRunner images agree to the digit). So every stored coordinate
is multiplied by MK = 2.5 on the way in.
"""
from PIL import Image
import json
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS_DIR = os.path.join(BASE, "assets")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "map_assets.h")

# the v1.13 coords we vendor are the 2014's / 2.5 (see the module doc)
MK = 2.5


# the 2014's own MapContents.json, extracted from runIII.swf: the decoration
# positions are ALREADY in the design space, so these are used verbatim.
DESIGN_CONTENTS = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                               "..", "swf_orig", "map_contents.json")


def image_to_rgba(im):
    w, h = im.size
    pixels = list(im.getdata())
    data = []
    for r, g, b, a in pixels:
        data.append((a << 24) | (r << 16) | (g << 8) | b)
    return w, h, data


def write_frame_array(f, name, w, h, data):
    f.write(f"static const uint32_t {name}[] = {{\n")
    for y in range(h):
        f.write("  ")
        for x in range(w):
            f.write(f"0x{data[y * w + x]:08X},")
        f.write("\n")
    f.write("};\n")


os.makedirs(os.path.dirname(OUT), exist_ok=True)


def dxy(ox, oy):
    """Stored (v1.13) map coords -> the 2014's design units, rounded. No
    offset and one uniform factor: the placement rule is entirely the
    renderer's (k and the mask box), never a baked screen position."""
    return (int(round(ox * MK)), int(round(oy * MK)))


total_bytes = 0

with open(OUT, "w") as f:
    f.write("/* map_assets.h - baked map background + decorations for WASM rendering.\n")
    f.write(" * Generated by bake_map.py. Do not edit manually. */\n")
    f.write("#ifndef MAP_ASSETS_H\n#define MAP_ASSETS_H\n\n")
    f.write("#include <stdint.h>\n\n")

    # ===== MAP MASK (the original's own frame) =====
    # Drawn at NATIVE size and scaled to 2k at run time (the 2014's bitmap
    # scale). It is a black frame with an organic inner edge: 91% of it is
    # transparent, the opaque part is the map's vignette, and it is added ON TOP
    # of the content container in MapMenu.create — so it crops the map.
    mask_path = os.path.join(ASSETS_DIR, "images/map_mapmask.png")
    if not os.path.exists(mask_path):
        raise SystemExit(f"missing {mask_path}")
    mask = Image.open(mask_path).convert("RGBA")
    w, h, data = image_to_rgba(mask)
    write_frame_array(f, "map_mask", w, h, data)
    f.write(f"#define MAP_MASK_W {w}\n")
    f.write(f"#define MAP_MASK_H {h}\n\n")
    total_bytes += w * h * 4
    print(f"  map_mask: {w}x{h} (drawn at 2k)")

    # ===== DECORATION IMAGES =====
    # Native size, name -> (file, design x, design y). The positions are the
    # ORIGINAL's authored ones, from the 2014 MapContents.json (Planet, Teapot,
    # Snowflakes, DerpRunner); the four the v1.13 added are that file's numbers
    # x 2.5. Nothing is hand-placed and nothing is resized: the original draws
    # each image at its own pixel size x 2k, which is what the renderer does.
    with open(DESIGN_CONTENTS) as fh:
        _orig = json.load(fh)
    _orig_img = _orig.get("images", {})
    try:
        with open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                               "..", "swf_orig", "map_contents_113.json")) as fh:
            _v113_img = json.load(fh).get("images", {})
    except FileNotFoundError:
        _v113_img = {}

    def authored(name):
        """A decoration's authored design position, or None."""
        if name in _orig_img:
            return int(_orig_img[name]["x"]), int(_orig_img[name]["y"])
        if name in _v113_img:
            return dxy(_v113_img[name]["x"], _v113_img[name]["y"])
        return None

    DECORATIONS = [
        ("deco_planet",     "images/map_planet.png",         "Planet"),
        ("deco_teapot",     "images/map_teapot.png",         "Teapot"),
        ("deco_wormhole",   "images/map_wormhole.png",       "Wormhole"),
        ("deco_snowflakes", "images/map_snowflakes.png",     "Snowflakes"),
        ("deco_derp",       "images/map_derprunner.png",     "DerpRunner"),
        ("deco_battery",    "images/map_battery.png",        "Battery"),
        ("deco_belt0",      "images/map_planetoidbelt0.png", "PlanetoidBelt0"),
        ("deco_belt1",      "images/map_planetoidbelt1.png", "PlanetoidBelt1"),
    ]

    deco_entries = []
    deco_boxes = []   # design-space footprints, for the map's own extent
    for dname, drel, src in DECORATIONS:
        dpath = os.path.join(ASSETS_DIR, drel)
        if not os.path.exists(dpath):
            print(f"  {dname}: NOT FOUND")
            continue
        if authored(src) is None:
            print(f"  {dname}: no authored position, skipped")
            continue
        dim = Image.open(dpath).convert("RGBA")
        w, h, data = image_to_rgba(dim)
        write_frame_array(f, dname, w, h, data)
        f.write(f"#define {dname}_W {w}\n")
        f.write(f"#define {dname}_H {h}\n\n")
        total_bytes += w * h * 4
        print(f"  {dname}: {w}x{h} at {authored(src)}")
        deco_entries.append(dname)
        dx, dy = authored(src)
        deco_boxes.append((dx, dy, dx + w, dy + h))

    f.write("/* Decoration struct: native pixels, design-unit position. */\n")
    f.write("typedef struct {\n")
    f.write("  const uint32_t *pix;\n")
    f.write("  int w, h, x, y;\n")
    f.write("} map_deco_t;\n\n")

    f.write(f"#define MAP_DECO_COUNT {len(deco_entries)}\n\n")

    f.write("static const map_deco_t map_decorations[] = {\n")
    for dname, drel, src in DECORATIONS:
        if dname in deco_entries:
            cx, cy = authored(src)
            f.write(f"  {{ {dname}, {dname}_W, {dname}_H, {cx}, {cy} }},\n")
    f.write("};\n\n")

    # ===== TUNNEL NODE POSITIONS =====
    # ===== TUNNEL NODES: first waypoints straight from the original map =====
    # (orig_map.json, vendored from the decompiled SWF's mapcontents).
    # Format: id, kind(0=name,1=letter), x, y, r, g, b — x/y MUST match the
    # path's first waypoint (asserted below) and story.js T[] positions.
    # Colors/kind are our display layer.
    TUNNELS_DATA = [
        # id, kind, x, y, r, g, b
        (0,  0, 0, 0,         125,211,252),   # Primary
        (1,  0, 400, 420,     147,197,253),   # Home 0
        (2,  0, 290, 315,     147,197,253),   # Home 1
        (3,  0, 290, 315,     147,197,253),   # Home 2
        (4,  0, 62, 314,      147,197,253),   # Home 3
        (5,  1, 1796, 0,       94,234,212),   # A
        (6,  1, 1440, 264,    252,211,77),    # B
        (7,  1, 1285, 637,    134,239,172),   # D
        (8,  1, 1817, 306,    216,180,254),   # G
        (9,  1, 2040, 324,    196,181,253),   # L
        (10, 1, 1200, 240,    240,171,252),   # M
        (11, 1, 2160, 394,    251,146,60),    # T
        (12, 0, 540, 138,     191,219,254),   # Winter
        (13, 0, 1000, 212,     30,27,75),     # Dark
        (14, 0, 1200, 240,    167,139,250),   # Boxes
        (15, 0, 1016, 47,      96,165,250),   # Memory
        (16, 0, 940, 404,     103,232,249),   # River
        (17, 1, 2476, 103,    192,132,252),   # Wormhole C
        (18, 1, 2509, 250,    192,132,252),   # Wormhole H
        (19, 1, 2476, -14,    192,132,252),   # Wormhole I
        (20, 1, 3021, 219,    192,132,252),   # Wormhole J
        (21, 1, 2767, 188,    192,132,252),   # Wormhole K
        (22, 1, 2180, -40,    192,132,252),   # Wormhole N
        (23, 1, 2950, 89,     192,132,252),   # Wormhole Space
        (24, 0, 672, -22,      52,211,153),   # Newly Formed
        (25, 0, 3327, 204,    251,191,36),    # Runway 0
        (26, 0, 3784, 310,    251,191,36),    # Runway 1
        (27, 0, 1305, 133,     45,212,191),   # Coordination
        (28, 1, 1440, 264,    167,139,250),   # U
        (29, 1, 400, 420,      52,211,153),   # W
        # --- custom extended tunnels (node = first waypoint below) ---
        (30, 1, 1650, 140,     94,234,212),   # F (Primary shortcut spur)
        (31, 1, 650, 520,     191,219,254),   # S (Winter snow spur)
        (32, 1, 1500, 80,     167,139,250),   # V (Boxes halls)
        (33, 1, 2400, 300,    192,132,252),   # Wormhole X (Primary's end)
        (34, 0, 4520, 270,    103,232,249),   # Far Shore (past Wormhole X)
        (35, 0, 6180, 490,    240,171,252),   # Far Drift (beyond the Shore)
        (36, 1, 3400, 120,    192,132,252),   # X-Rift (Wormhole X branch)
        (37, 1, 2850, 170,    192,132,252),   # X-Echo (Wormhole X branch)
        (38, 1, 5240, 490,    103,232,249),   # Shoal (Far Shore branch)
        (39, 1, 5960, 540,    103,232,249),   # Reef (Far Shore branch)
        (40, 1, 6840, 660,    240,171,252),   # Wake (Far Drift branch)
        (41, 1, 6620, 620,    240,171,252),   # Ember (Far Drift branch)
        # --- recovered original paths (real levels, never linked on the map) ---
        (42, 0, 520, 540,     147,197,253),   # Home Plan A (under Home 0)
        (43, 0, 180, 470,     147,197,253),   # Home Plan C (under Home 2)
        (44, 1, 2320, -130,   192,132,252),   # Wormhole P (off Wormhole N)
        (45, 1, 2620, -40,    192,132,252),   # The Crossing (P's single level)
    ]

    # Custom waypoint polylines (original map coords) for ids 30+.
    # The extended world is laid out in three tiers sweeping right: Wormhole X
    # carries its 140 checkpoints along the top, Far Shore the middle, Far
    # Drift the bottom, with each sub-branch folding off its main run.
    CUSTOM_WP = {
        30: [(1650, 140), (1500, 60), (1380, -20)],
        31: [(650, 520), (500, 560), (380, 620)],
        32: [(1500, 80), (1620, 140), (1740, 180)],
        33: [(2400, 300), (2620, 230), (2850, 170), (3100, 130), (3400, 120),
             (3700, 130), (4000, 160), (4280, 210), (4520, 270)],
        34: [(4520, 270), (4760, 340), (5000, 420), (5240, 490), (5480, 540),
             (5720, 560), (5960, 540), (6180, 490)],
        35: [(6180, 490), (6400, 560), (6620, 620), (6840, 660), (7060, 670),
             (7280, 650), (7480, 600)],
        36: [(3400, 120), (3500, 40), (3620, -10), (3750, -30)],
        37: [(2850, 170), (2800, 80), (2700, 10), (2560, -20)],
        38: [(5240, 490), (5320, 570), (5380, 650), (5420, 730)],
        39: [(5960, 540), (6020, 460), (6080, 390), (6120, 300)],
        40: [(6840, 660), (6980, 700), (7120, 720)],
        41: [(6620, 620), (6620, 520), (6600, 430), (6570, 340)],
        # recovered original paths: short hand-placed runs under their parents
        42: [(520, 540), (660, 600), (800, 640)],
        43: [(180, 470), (60, 520), (-60, 560)],
        44: [(2320, -130), (2450, -170), (2560, -140)],
        45: [(2620, -40), (2700, -80), (2780, -110)],
    }

    import json as _json
    _omap = _json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                         "orig_map.json")))
    _wp_by_id = {t['id']: t['waypoints'] for t in _omap['tunnels']}
    assert sorted(_wp_by_id) == list(range(30)), "orig_map.json must hold ids 0-29"
    for _cid, _pts in CUSTOM_WP.items():
        assert _cid not in _wp_by_id, f"custom id {_cid} collides with original"
        _wp_by_id[_cid] = [[float(x), float(y)] for x, y in _pts]

    # ===== THE MAP'S OWN DESIGN EXTENT =====
    # Everything the map draws lies inside this box, so the renderer can derive
    # the parchment's span and the pan's reach from it instead of a constant
    # that only matched one window size.
    # the paths are still in the v1.13 units here, the decorations already in
    # design units, so convert the waypoints (only) on the way in
    _wp_design = [dxy(x, y) for pts in _wp_by_id.values() for x, y in pts]
    _ex0 = min(p[0] for p in _wp_design)
    _ex1 = max(p[0] for p in _wp_design)
    _ey0 = min(p[1] for p in _wp_design)
    _ey1 = max(p[1] for p in _wp_design)
    for bx0, by0, bx1, by1 in deco_boxes:
        _ex0 = min(_ex0, bx0); _ex1 = max(_ex1, bx1)
        _ey0 = min(_ey0, by0); _ey1 = max(_ey1, by1)
    f.write("/* The map's own design extent (design units): the parchment's world span\n")
    f.write(" * and the pan's reach derive from it. */\n")
    f.write(f"#define MAP_DESIGN_MINX {_ex0}\n")
    f.write(f"#define MAP_DESIGN_MAXX {_ex1}\n")
    f.write(f"#define MAP_DESIGN_MINY {_ey0}\n")
    f.write(f"#define MAP_DESIGN_MAXY {_ey1}\n\n")
    print(f"  design extent x {_ex0}..{_ex1} y {_ey0}..{_ey1}")

    f.write("/* Tunnel node data: id, kind(0=name,1=letter), x, y, r, g, b.\n")
    f.write(" * Node coords = original first waypoints, in the 2014's design units\n")
    f.write(" * (the renderer applies k). Ids 30+ are custom extended tunnels\n")
    f.write(" * (hand-placed, node = path start); 33/34/35 are the 140-checkpoint\n")
    f.write(" * main runs, 36-41 their branches, 42-45 the recovered original paths. */\n")
    f.write("#define MAP_TUNNEL_COUNT 46\n\n")

    f.write("typedef struct {\n")
    f.write("  int16_t x, y;\n")
    f.write("  uint8_t r, g, b;\n")
    f.write("  uint8_t kind; /* 0=name, 1=letter */\n")
    f.write("} map_node_t;\n\n")

    f.write("static const map_node_t map_nodes[MAP_TUNNEL_COUNT] = {\n")
    for tid, kind, ox, oy, r, g, b in TUNNELS_DATA:
        # node MUST equal the path's first waypoint (original layout guarantee).
        # The table's x/y are that waypoint to the integer, so they agree here
        # to well under the 2.5 design conversion; the node is then taken from
        # the PATH so the two cannot drift apart again.
        w0 = _wp_by_id[tid][0]
        assert abs(w0[0] - ox) <= 0.6 and abs(w0[1] - oy) <= 0.6, \
            f"node {tid} != first waypoint"
        cx, cy = dxy(w0[0], w0[1])
        f.write(f"  {{ {cx}, {cy}, {r}, {g}, {b}, {kind} }}, /* {tid} */\n")
    f.write("};\n\n")

    # ===== PATH POLYLINES: the original drawn curves (screen coords) =====
    # Checkpoints are spaced evenly along these; the map draws them as-is.
    f.write("/* Path polylines: x0,y0,x1,y1,... per tunnel (screen coords). */\n")
    for tid, kind, ox, oy, r, g, b in TUNNELS_DATA:
        pts = []
        for wx, wy in _wp_by_id[tid]:
            cx, cy = dxy(wx, wy)
            pts.append(f"{cx},{cy}")
        f.write(f"static const int16_t map_wp_{tid}[] = {{{','.join(pts)}}};\n")
    f.write("static const int16_t *map_wp[MAP_TUNNEL_COUNT] = {\n")
    for tid, kind, ox, oy, r, g, b in TUNNELS_DATA:
        f.write(f"  map_wp_{tid},\n")
    f.write("};\n")
    f.write("static const uint8_t map_wp_n[MAP_TUNNEL_COUNT] = {\n")
    for tid, kind, ox, oy, r, g, b in TUNNELS_DATA:
        n = len(_wp_by_id[tid])
        assert 2 <= n <= 255, f"path {tid} waypoint count {n}"
        f.write(f"  {n}, /* {tid} */\n")
    f.write("};\n\n")

    # ===== TUNNEL NAMES (short, for display) — ids 0-35 =====
    NAMES = [
        "Primary", "Home 0", "Home 1", "Home 2", "Home 3",
        "A", "B", "D", "G", "L", "M", "T",
        "Winter", "Dark", "Boxes", "Memory", "River",
        "WH C", "WH H", "WH I", "WH J", "WH K", "WH N", "WH Spc",
        "Newly", "Runway0", "Runway1", "Coord",
        "U", "W",
        "F", "S", "V", "WH X", "Shore", "Drift",
        "X-Rift", "X-Echo", "Shoal", "Reef", "Wake", "Ember",
        "Plan A", "Plan C", "WH P", "Crossing",
    ]
    assert len(NAMES) == len(TUNNELS_DATA) == 46

    f.write("/* Tunnel name strings */\n")
    f.write("static const char *map_tunnel_names[MAP_TUNNEL_COUNT] = {\n")
    for i, name in enumerate(NAMES):
        f.write(f'  "{name}", /* {i} */\n')
    f.write("};\n\n")

    f.write("#endif /* MAP_ASSETS_H */\n")

print(f"\nTotal map assets: {total_bytes} bytes ({total_bytes/1024:.0f} KB)")
print(f"Done: {OUT}")
