#!/usr/bin/env python3
"""Bake the 2014 menu's bitmaps into menu_assets.h + menu_metrics.h.

The source is the 2014 edition's own asset set, extracted from runIII.swf into
swf_orig/imgs2014/ (see swf_orig/extract_*.py). Byte-for-byte the same art the
original draws, so a menu built from these can be compared against it directly.

TWO HEADERS, ONE FOR EACH AUDIENCE:

  * menu_metrics.h holds only the NATIVE sizes (`MENU_TITLE_W` ...). Both
    run3.c (which owns the menu's layout) and render.c (which draws it) include
    it, so the hit boxes and the pixels are derived from the same numbers and
    cannot drift apart.
  * menu_assets.h holds the pixel arrays and is included ONCE, by render.c, so
    the megabyte of art is not compiled into the engine twice.

Sizes are NATIVE PIXELS. The 2014 draws every bitmap at TWICE its design scale
(ScaledAssets sets Bitmap.scaleX = 2 * scaleX), so the renderer multiplies by
`2 * k` with `k = min(BASE_W/3000, BASE_H/2000)` — the same k the map uses.
That rule lives in the renderer, never here.
"""
from PIL import Image
import glob
import os

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.dirname(HERE)
IMGS = os.path.join(BASE, "swf_orig", "imgs2014")
IMG_H = os.path.join(HERE, "menu_assets.h")
MET_H = os.path.join(HERE, "menu_metrics.h")

# (var name, metric prefix, the asset path inside the SWF)
ASSETS = [
    ("menu_title",       "MENU_TITLE",       "menu/Run3.png"),
    ("menu_play",        "MENU_PLAY",        "menu/PlayGame.png"),
    ("menu_leaderboards", "MENU_LEADERBOARDS", "menu/Leaderboards.png"),
    ("menu_achievements", "MENU_ACHIEVEMENTS", "menu/Achievements.png"),
    ("menu_edit",        "MENU_EDIT",        "menu/EditIcon.png"),
    ("menu_credits",     "MENU_CREDITS",     "menu/CreditsIcon.png"),
    ("menu_shop",        "MENU_SHOP",        "menu/Shop.png"),
    ("menu_mapicon",     "MENU_MAPICON",     "map/MapIcon.png"),
]


def source_for(path):
    """The extractor names a bitmap by its asset path with '/' -> '_':
    img/menu/Run3.png -> <id>___ASSET__img_menu_run3_png.png"""
    tail = "img_" + path.lower().replace("/", "_").replace(".png", "") + "_png.png"
    hits = [f for f in glob.glob(os.path.join(IMGS, "*.png"))
            if os.path.basename(f).lower().endswith(tail)]
    if len(hits) != 1:
        raise SystemExit(f"{path}: expected 1 source, found {len(hits)}")
    return hits[0]


def image_to_rgba(im):
    w, h = im.size
    return w, h, [(a << 24) | (r << 16) | (g << 8) | b
                  for r, g, b, a in im.convert("RGBA").getdata()]


def write_frame_array(f, name, w, h, data):
    f.write(f"static const uint32_t {name}[] = {{\n")
    for y in range(h):
        f.write("  ")
        for x in range(w):
            f.write(f"0x{data[y * w + x]:08X},")
        f.write("\n")
    f.write("};\n")


baked = []
for var, prefix, path in ASSETS:
    im = Image.open(source_for(path))
    baked.append((var, prefix, path, *image_to_rgba(im)))

with open(MET_H, "w", newline="\n") as f:
    f.write("/* menu_metrics.h - the 2014 menu bitmaps' NATIVE sizes.\n"
            " * Generated by bake_menu.py. Do not edit manually.\n"
            " *\n"
            " * Native pixels, not screen pixels: the renderer draws each one at\n"
            " * `2 * k` with k = min(BASE_W/3000, BASE_H/2000) (see\n"
            " * GUI_2014.md). Included by run3.c AND render.c so the menu's layout\n"
            " * and its hit tests read the same numbers. */\n"
            "#ifndef MENU_METRICS_H\n#define MENU_METRICS_H\n\n")
    for var, prefix, path, w, h, _ in baked:
        f.write(f"#define {prefix}_W {w}\t/* {path} */\n")
        f.write(f"#define {prefix}_H {h}\n")
    f.write("\n#endif /* MENU_METRICS_H */\n")

with open(IMG_H, "w", newline="\n") as f:
    f.write("/* menu_assets.h - the 2014 menu's own bitmaps, baked for WASM.\n"
            " * Generated by bake_menu.py. Do not edit manually. */\n"
            "#ifndef MENU_ASSETS_H\n#define MENU_ASSETS_H\n\n"
            "#include <stdint.h>\n#include \"menu_metrics.h\"\n\n")
    for var, prefix, path, w, h, data in baked:
        f.write(f"/* {path} - {w}x{h} */\n")
        write_frame_array(f, var, w, h, data)
        f.write("\n")
    f.write("#endif /* MENU_ASSETS_H */\n")

print(f"wrote {MET_H}")
print(f"wrote {IMG_H} ({os.path.getsize(IMG_H)} bytes, {len(baked)} bitmaps)")
for var, prefix, path, w, h, _ in baked:
    print(f"  {prefix:20s} {w:4d}x{h:<4d} {path}")
