/* menu_metrics.h - the 2014 menu bitmaps' NATIVE sizes.
 * Generated by bake_menu.py. Do not edit manually.
 *
 * Native pixels, not screen pixels: the renderer draws each one at
 * `2 * k` with k = min(BASE_W/3000, BASE_H/2000) (see
 * GUI_2014.md). Included by run3.c AND render.c so the menu's layout
 * and its hit tests read the same numbers. */
#ifndef MENU_METRICS_H
#define MENU_METRICS_H

#define MENU_TITLE_W 642	/* menu/Run3.png */
#define MENU_TITLE_H 212
#define MENU_PLAY_W 298	/* menu/PlayGame.png */
#define MENU_PLAY_H 176
#define MENU_LEADERBOARDS_W 100	/* menu/Leaderboards.png */
#define MENU_LEADERBOARDS_H 100
#define MENU_ACHIEVEMENTS_W 100	/* menu/Achievements.png */
#define MENU_ACHIEVEMENTS_H 100
#define MENU_EDIT_W 131	/* menu/EditIcon.png */
#define MENU_EDIT_H 133
#define MENU_CREDITS_W 123	/* menu/CreditsIcon.png */
#define MENU_CREDITS_H 123
#define MENU_SHOP_W 64	/* menu/Shop.png */
#define MENU_SHOP_H 64
#define MENU_MAPICON_W 163	/* map/MapIcon.png */
#define MENU_MAPICON_H 135

#endif /* MENU_METRICS_H */
